FROM node:21.7.3-alpine as base

WORKDIR /app

COPY ["package.json", "./"]

RUN --mount=type=cache,target=./.npm \
  npm set cache ./.npm && \
  npm install --loglevel verbose
COPY . .
EXPOSE 8080
EXPOSE 5555
CMD ["node", "ace", "serve", "--watch"]
