<script lang="ts" setup>
import { ref } from 'vue'
import AppQuestionStatusBadge from './app_question_status_badge.vue'

export interface QuestionPreviewData {
  id: string
  statement: string
  difficulty: string
  status: string
  subjectName?: string
  topicName?: string
  options: Array<{ id: string; label: string; content: string; isCorrect: boolean }>
  solution?: string
  explanation?: string
  sourceMetadata?: {
    isAiGenerated?: boolean
    aiConfidenceScore?: number
    sourceExam?: string
  }
  relations?: Array<{
    relationType: 'SAME_AS' | 'SIMILAR_TO'
    targetQuestionStatement: string
    targetExamName?: string
  }>
}

interface Props {
  question: QuestionPreviewData
  showActions?: boolean
}

const props = defineProps<Props>()
const emit = defineEmits(['edit', 'moderate'])

const showSolution = ref(false)
const selectedOptionId = ref<string | null>(null)
</script>

<template>
  <div class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6 shadow-sm space-y-4">
    <!-- Header: Metadata & Status -->
    <div class="flex flex-wrap items-center justify-between gap-2 pb-3 border-b dark:border-gray-700">
      <div class="flex items-center gap-2">
        <span class="px-2 py-0.5 rounded text-xs font-semibold bg-primary-100 text-primary-800 dark:bg-primary-900 dark:text-primary-200">
          {{ question.subjectName || 'Disciplina' }}
        </span>
        <span v-if="question.topicName" class="text-xs text-gray-500 dark:text-gray-400">
          › {{ question.topicName }}
        </span>
        <span class="text-xs px-2 py-0.5 rounded bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300">
          {{ question.difficulty }}
        </span>
      </div>

      <div class="flex items-center gap-2">
        <AppQuestionStatusBadge :status="question.status" />
      </div>
    </div>

    <!-- AI Indicator Banner (if generated by AI) -->
    <div
      v-if="question.sourceMetadata?.isAiGenerated"
      class="flex items-center justify-between p-2.5 rounded-lg bg-purple-50 dark:bg-purple-950/40 border border-purple-200 dark:border-purple-800 text-xs text-purple-900 dark:text-purple-300"
    >
      <div class="flex items-center gap-2">
        <span>✨</span>
        <span class="font-medium">Conteúdo Extraído por Inteligência Artificial</span>
      </div>
      <div v-if="question.sourceMetadata.aiConfidenceScore" class="font-mono bg-purple-100 dark:bg-purple-900/60 px-2 py-0.5 rounded text-purple-800 dark:text-purple-200">
        Confiança do Modelo: {{ Math.round(question.sourceMetadata.aiConfidenceScore * 100) }}%
      </div>
    </div>

    <!-- Question Statement (Aluno Experience) -->
    <div class="text-gray-900 dark:text-gray-100 text-base leading-relaxed whitespace-pre-wrap font-serif">
      {{ question.statement }}
    </div>

    <!-- Options List -->
    <div class="space-y-2 pt-2">
      <div
        v-for="opt in question.options"
        :key="opt.id"
        :class="[
          'flex items-start p-3 rounded-lg border text-sm transition cursor-pointer',
          selectedOptionId === opt.id
            ? 'border-primary-500 bg-primary-50/50 dark:bg-primary-950/30 dark:border-primary-500'
            : 'border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-750',
          showSolution && opt.isCorrect ? 'border-emerald-500 bg-emerald-50 dark:bg-emerald-950/40 font-semibold' : ''
        ]"
        @click="selectedOptionId = opt.id"
      >
        <span
          :class="[
            'w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold mr-3 shrink-0',
            showSolution && opt.isCorrect
              ? 'bg-emerald-600 text-white'
              : selectedOptionId === opt.id
                ? 'bg-primary-600 text-white'
                : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300'
          ]"
        >
          {{ opt.label }}
        </span>
        <span class="text-gray-800 dark:text-gray-200 flex-1">
          {{ opt.content }}
        </span>
        <span v-if="showSolution && opt.isCorrect" class="text-xs text-emerald-600 dark:text-emerald-400 font-bold ml-2">
          (Gabarito Correto)
        </span>
      </div>
    </div>

    <!-- Solution / Explanation Toggle -->
    <div class="pt-2">
      <button
        type="button"
        class="text-xs text-primary-600 dark:text-primary-400 hover:underline font-medium focus:outline-none"
        @click="showSolution = !showSolution"
      >
        {{ showSolution ? 'Ocultar Resolução Explicativa ▲' : 'Ver Resolução & Explicação Didática ▼' }}
      </button>

      <div v-if="showSolution" class="mt-3 p-4 rounded-lg bg-gray-50 dark:bg-gray-900/60 border border-gray-200 dark:border-gray-700 space-y-3">
        <div v-if="question.solution">
          <span class="text-xs font-bold uppercase text-gray-500 dark:text-gray-400 block mb-1">Passo a Passo da Resolução:</span>
          <p class="text-sm text-gray-800 dark:text-gray-200 whitespace-pre-wrap">{{ question.solution }}</p>
        </div>
        <div v-if="question.explanation">
          <span class="text-xs font-bold uppercase text-gray-500 dark:text-gray-400 block mb-1">Fundamentação Teórica:</span>
          <p class="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap">{{ question.explanation }}</p>
        </div>
      </div>
    </div>

    <!-- Question Relations (SAME_AS & SIMILAR_TO) -->
    <div v-if="question.relations && question.relations.length > 0" class="pt-2 border-t dark:border-gray-700">
      <span class="text-xs font-semibold text-gray-500 dark:text-gray-400 block mb-2">
        {{ $t('academic.question.related') }}:
      </span>
      <div class="space-y-1">
        <div
          v-for="(rel, idx) in question.relations"
          :key="idx"
          class="flex items-center gap-2 text-xs text-gray-600 dark:text-gray-300 p-2 rounded bg-gray-50 dark:bg-gray-850"
        >
          <span :class="rel.relationType === 'SAME_AS' ? 'text-emerald-600 font-bold' : 'text-blue-600 font-bold'">
            {{ rel.relationType === 'SAME_AS' ? '✓ Mesma Questão' : '≈ Semelhante / Variação' }}
          </span>
          <span class="text-gray-400">•</span>
          <span class="truncate flex-1">{{ rel.targetQuestionStatement }}</span>
          <span v-if="rel.targetExamName" class="text-gray-400 text-2xs">({{ rel.targetExamName }})</span>
        </div>
      </div>
    </div>

    <!-- Actions (Edit / Moderate) -->
    <div v-if="showActions" class="flex justify-end gap-2 pt-3 border-t dark:border-gray-700">
      <button
        class="text-xs px-3 py-1.5 rounded-lg border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 font-medium"
        @click="emit('edit', question)"
      >
        {{ $t('academic.question.edit') }}
      </button>
      <button
        class="text-xs px-3 py-1.5 rounded-lg bg-primary-600 hover:bg-primary-700 text-white font-medium shadow-sm"
        @click="emit('moderate', question)"
      >
        {{ $t('academic.question.review') }}
      </button>
    </div>
  </div>
</template>
